apiVersion: v1
kind: Service
metadata:
  name: sample-service
spec:
  type: LoadBalancer
  # deployment.yamlで指定したmatchLabelsの文字列と同じものを指定する必要があります。
  selector:
    app: sample-app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80